In [26]:
import pandas as pd
import numpy as np

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
S1=pd.read_csv("/content/drive/MyDrive/NFT Price Prediction/dataset/solution1.csv")
S2=pd.read_csv("/content/drive/MyDrive/NFT Price Prediction/dataset/solution2.csv")
S3=pd.read_csv("/content/drive/MyDrive/NFT Price Prediction/dataset/solution3.csv")
S4=pd.read_csv("/content/drive/MyDrive/NFT Price Prediction/dataset/solution4.csv")
S5=pd.read_csv("/content/drive/MyDrive/NFT Price Prediction/dataset/solution5.csv")

In [29]:
S1.head() #22

   global_index  last_sale_price
0           0.0         1.087091
1           1.0         0.222507
2           2.0         3.253762
3           3.0         1.087091
4           4.0         0.741355

In [30]:
S2.head() #26

   global_index  last_sale_price
0           0.0         1.040449
1           1.0         0.249687
2           2.0         2.798193
3           3.0         1.040449
4           4.0         0.976794

In [31]:
S3.head() #34

   global_index  last_sale_price
0           0.0         1.009332
1           1.0         1.028892
2           2.0         2.736051
3           3.0         1.009332
4           4.0         0.760658

In [32]:
S4.head() # 29

   global_index  last_sale_price
0           0.0         1.049059
1           1.0         0.814101
2           2.0         3.180232
3           3.0         1.087526
4           4.0         0.681454

In [33]:
S5.head() #32

   global_index  last_sale_price
0           0.0         0.960619
1           1.0         1.171245
2           2.0         2.666511
3           3.0         0.953556
4           4.0         0.833175

# Final Solution 1

In [34]:
f1=S1.copy()
f1['last_sale_price']=(S1['last_sale_price']+S3['last_sale_price']+S5['last_sale_price'])/3
f1.head()

   global_index  last_sale_price
0           0.0         1.019014
1           1.0         0.807548
2           2.0         2.885441
3           3.0         1.016660
4           4.0         0.778396

In [35]:
f1.to_csv("result35_22_32_34.csv",index=False)

# Final Solution 2

## Geometric Mean

In [36]:
GM=S1.copy()
GM['last_sale_price']=(S1['last_sale_price']*S3['last_sale_price']*S5['last_sale_price'])**(1/3)
GM.head()

   global_index  last_sale_price
0           0.0         1.017693
1           1.0         0.644843
2           2.0         2.873985
3           3.0         1.015193
4           4.0         0.777411

## Simple Mean 1

In [37]:
SM1=S1.copy()
SM1['last_sale_price']=(S1['last_sale_price']
                        +S5['last_sale_price']
                        +S3['last_sale_price']
                        +GM['last_sale_price']+
                        f1['last_sale_price'])/5
SM1.head()

   global_index  last_sale_price
0           0.0         1.018750
1           1.0         0.775007
2           2.0         2.883150
3           3.0         1.016366
4           4.0         0.778199

## Simple Mean2

In [38]:
SM2=S1.copy()
SM2['last_sale_price']=(S1['last_sale_price']
                        +S2['last_sale_price']
                        +S4['last_sale_price']
                        )/3
SM2.head()

   global_index  last_sale_price
0           0.0         1.058866
1           1.0         0.428765
2           2.0         3.077396
3           3.0         1.071689
4           4.0         0.799867

In [39]:
f2=S1.copy()
f2['last_sale_price']=(S1['last_sale_price']
                        +S5['last_sale_price']
                        +S3['last_sale_price']
                        +f1['last_sale_price']
                        +GM['last_sale_price']
                        +SM1['last_sale_price']
                        +S5['last_sale_price']
                        +SM2['last_sale_price'])/8
f2.head()

   global_index  last_sale_price
0           0.0         1.016498
1           1.0         0.781257
2           2.0         2.880351
3           3.0         1.015430
4           4.0         0.787779

In [40]:
f2.to_csv("result38_M.csv",index=False)